spring.application.name=florgest-backend

# Configuración de Base de Datos H2 (Basado en archivo para persistencia)
spring.datasource.url=jdbc:h2:file:./data/florgest_db
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver

# Habilitar consola de H2 para poder ver la BD en http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Puerto del servidor
server.port=8080
